const mongoose=require("mongoose");
const Schema=mongoose.Schema;

const AnalyticsSchema=new Schema({
    creator:{
        type:Schema.Types.ObjectId,
        ref:"User",
        required:true,
    },
    currentMonth:{
        MonthNo:{
            type:Number
        },
        Orders:{
              data:[0,0,0,0],
              Items:[
              {
                  data:[0,0,0,0,0,0,0],
              },
              {
                  data:[0,0,0,0,0,0,0],
              },
              {
                  data:[0,0,0,0,0,0,0],
              },
              {
                  data:[0,0,0,0,0,0,0],
              },
          ]
        },
        Visits:{
              data:[0,0,0,0],
              Items:[
              {
                  data:[0,0,0,0,0,0,0],
              },
              {
                  data:[0,0,0,0,0,0,0],
              },
              {
                  data:[0,0,0,0,0,0,0],
              },
              {
                  data:[0,0,0,0,0,0,0],
              },
          ]
        },
        Revenue:{
              data:[0,0,0,0],
              Items:[
              {
                  data:[0,0,0,0,0,0,0],
              },
              {
                  data:[0,0,0,0,0,0,0],
              },
              {
                  data:[0,0,0,0,0,0,0],
              },
              {
                  data:[0,0,0,0,0,0,0],
              },
          ]
        }
    }
})

module.exports=mongoose.model("Analytics",AnalyticsSchema);